### PR TITLE
Prepare version ready to be submitted to PyPI

### PR DESCRIPTION
**Pull request by pjuda**
Minor changes for correct submission to PyPI

### CODE REVIEW

**Comment by jaegglic** [comment]
This is looking good, thanks.

**Comment by jaegglic** [comment]
Sorry, I just wanted to review it, not closing it.

**Comment by pjuda** [comment]
Thanks for the feedback, Christoph!

I removed requirements.txt and updated setup.py. There was already some code specifying numpy as required packaged in setup.py but in a somehow convoluted way. I removed the test dependencies and specified numpy and scipy as required dependencies without any versions in setup.py The requirements.txt is now removed.

 - Should I specify any minimal version for numpy and scipy?

Cheers,
Przemek

**Comment by jaegglic** [comment]
Ok, I think the setup.py should work as it is right now. Thank you very much

**Comment by pjuda** [comment]
Merci Christoph!
I merge the commit

**Pull request merged**
